# ==============================
# CONFIGURACIÓN DEL SERVIDOR
# ==============================
server.port=8080

# ==============================
# CONEXIÓN A MONGODB
# ==============================
spring.data.mongodb.uri=mongodb://localhost:27017/bienesraices
spring.data.mongodb.database=bienesraices

# ==============================
# CONFIGURACIÓN GENERAL
# ==============================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Muestra las operaciones en consola
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
